# Generated by Django 4.0.5 on 2022-06-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('rented', 'مؤجر'), ('Available', 'متاح'), ('sold', 'مباع')], max_length=50, verbose_name='حالة الكتاب : '),
        ),
    ]
